project:
  type: website
  output-dir: _site

website:
  title: "RiX Static Export Showcase"
  navbar:
    left:
      - href: "Analysis/report.qmd"
        text: "report"
      - href: "Analysis/slides.qmd"
        text: "slides"

format:
  html:
    toc: true
